keys:
  - users:
    - &orlando age10uea7efn6cg8pj88vtmvm8k90e3a0sy5zs4qtserlrj3gs07fq9s5dxj47
  - hosts:
    - &trinity age1xx7wq5gugwsjjxwv4gc0d6sgmq3q0h8qk3crn7erp33fsg2fn93sqlf3e0
    - &weasel age1573tkxh4k6rg4vzaw3x9wuy9addv4ff607xk73rf20vpmc60jv3qpxwatd
    - &neo  age1w533h944wruvaxuvxgamftcg2a5khj0ukdymz3uctf0t4ggy3ccq7taykk
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *orlando
      - *trinity
      - *weasel
      - *neo
