# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "thunderbolt" "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd" "ssd" "noatime" "space_cache=v2" ];
    };

  boot.initrd.luks.devices."system".device = "/dev/disk/by-partlabel/SOLID-CRYPT";

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "ssd" "noatime" "space_cache=v2"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "ssd" "noatime" "space_cache=v2"];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" "compress=zstd" "ssd" "noatime" "space_cache=v2"];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@var/log" "compress=zstd" "ssd" "noatime" "space_cache=v2"];
    };

  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-label/NIX-SYSTEM";
      fsType = "btrfs";
      options = [ "subvol=@var/lib/docker" "compress=zstd" "ssd" "noatime" "space_cache=v2"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIX-EFI";
      fsType = "vfat";
    };

  swapDevices = [ { device = "/swap/swapfile"; } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp74s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp73s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.opengl.driSupport = true;
  hardware.opengl.driSupport32Bit = true;
  hardware.opengl.extraPackages = [ pkgs.amdvlk ];
  hardware.keyboard.qmk.enable = true;
}
